name: Avesha Kubeslice Controller Installation
description: For Issues Related to Kubeslice controller Installation
title: "Give a title to your Problem !!  "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      

      
  - type: input
    id: ChartVersion
    attributes:
      label: Enter Kubeslice controller Chart Version
      description: Tell us the Chart Version, in which you are facing the problem.
      placeholder: 0.0.0
    validations:
      required: true
  
  - type: dropdown
    id: OS
    attributes:
      label: Tell us your operating System name.
      description: you can choose multiple Operating System, if you are using.
      multiple: true
      options:
        - Ubuntu  OS
        - Mac     OS
        - Amazon  OS
        - Redhat  OS
        - Windows OS
        
  - type: dropdown
    id: which-section
    attributes:
      label: in which section are you facing an issue ?
      description: if you are facing an issue in validation or creation, you can choose multiple section according to your issue.
      multiple: true
      options: 
        - In Installing the certificate manager
        - In Creation of values File
        - In Creation of Project
    validations:
      required: true
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened ? According to above selected Section please describe here.
      description: Also tell us, what did you expect to happen ?
      placeholder: Tell us what you see !
      value: "A bug happened!"
    validations:
      required: true
        
  - type: textarea
    id: logs
    attributes:
      label: Provide the Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of conduct. [ Visit Avesha for more info ](https://avesha.io)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
