name: Avesha KubeSice controller Bug
description: For Bugs Related to Kubeslice controller.
title: "Give a title to your Bug !!  "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened ? Please describe about the bug ?
      placeholder: Also tell us, what did you expect to happen and what else happened ?
      description: Tell us more about bug
    validations:
      required: false
      
  - type: textarea
    id: line-number
    attributes:
      label: Are you facing an bug because of any line in the code for specific file ?
      description: please put the line number here with file name.
      placeholder: "ex: line number: 3, file name: project.yaml"
    validations:
      required: false
      
  - type: textarea
    id: specific-file
    attributes:
      label: Can you please tell us more about the bug, such as what happened and what you expected to happen ?
      placeholder: please describe your problem with as much as info you can
      description: Tell us File name !
    validations:
      required: false
      
  
  - type: textarea
    id: edge-cases
    attributes:
      label: Are you facing an issue related to edge cases, if yes, please give us more info ?
      placeholder: please put the edge cases detail here or any other info which you want to share with us ragrding edge cases.
      description: Tell us Edge case details !
    validations:
      required: false
      
        
  - type: textarea
    id: logs
    attributes:
      label: please put log output for your concerned problem.
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
      
  - type: textarea
    id: scenario
    attributes:
      label: please tell us in more detail if you are following any specific scenario.
      placeholder: please provide all the scenario details, it will be helpful for troubleshooting the concern problem.
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    validations:
      required: false
      
  - type: textarea
    id: improvement
    attributes:
      label: Any other issue which you are facing or any other improvement you want from Avesha ?
      placeholder: if your problem don't comes under the above given cateogry use this box to give us info for your specific problem or any improvement which you are looking from avesha, tell us ?
      description: Describe your Specific Problem or the improvement, which you are finding from our side.
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of conduct. [ Visit Avesha for more info ](https://avesha.io)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
