name: Avesha KubeSice-cotroller issue
description: For Bugs Related to Kubeslice controller installation
title: "Give a title to your Problem !!  "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened, any specific process in which you are facing the issue ?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: false
      
  - type: textarea
    id: line-number
    attributes:
      label: Any specific code line, in which you are facing issue ?
      description: plase put the line number here ....
      placeholder: Tell us Line number !
      value: "A bug happened!"
    validations:
      required: false
      
  - type: textarea
    id: specific-file
    attributes:
      label: Any specific File, in which you are facing issue ?
      description: plase put the file name here, also you can tell us the line number for a specific file in which you are facing the issue.
      placeholder: Tell us File name !
      value: "A bug happened!"
    validations:
      required: false
      
  
  - type: textarea
    id: edge-cases
    attributes:
      label: Are you facing an issue related to edge cases, if yes, please give us more info ?
      description: plase put the edge cases detail here or any other info which you want to share with us ragrding edge cases.
      placeholder: Tell us Edge case detail !
      value: "A bug happened!"
    validations:
      required: false
      
        
  - type: textarea
    id: logs
    attributes:
      label: please put log output for your concerned problem.
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
      
  - type: textarea
    id: scenario
    attributes:
      label: please tell us more detail if you are following any specific scenario.
      placeholder: 
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of conduct. [ Visit Avesha for more info ](https://avesha.io)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
